//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpAIAssistant.Web.Account
{
    public partial class ExternalLoginCallback
    {
        // No controls defined in this page - it performs OAuth callback logic and redirects
    }
}
